baseURL = 'https://aventures-sonores.github.io/test-site-hugo/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
author = 'Aventures Sonores'
description = 'Our site'
favicon =  '/favicon.ico'

[searchEngines]
name = 'Google'
activated = true
icon = ['fab' ,'fa-google']
url = 'https://google.com/search'